### PR TITLE
Add wl_ugps_external

### PR DESCRIPTION
**Pull request by clydemcqueen**
Hi, folks -- I'm submitting my super-simple "Water Linked UGPS External" extension for the extensions repository. Thanks.

### CODE REVIEW

**Review by Williangalvani — APPROVED** [review]
Nice!

**Review by Williangalvani — APPROVED** [review]

**Comment by Williangalvani** [comment]
@clydemcqueen I just noticed you don't have any tags in your github repo, wee need those for loading the readme as you are doing https://github.com/clydemcqueen/wl_ugps_external_extension/blob/main/Dockerfile#L59

**Comment by clydemcqueen** [comment]
@Williangalvani Thanks for the help. I think I fixed it -- can you take another look?

**Comment by Williangalvani** [comment]
perfect!

**Pull request merged**
