### PR TITLE
repos: patrickelectric: node-red: Fist commit

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by ES-Alexander** [comment]
Consolidate is failing because of the trailing comma [here](https://github.com/patrickelectric/blueos-node-red/blob/master/Dockerfile#L48C13-L48C14) (we're handling the labels using JSON, which doesn't allow a comma after the last item in a list).

**Comment by patrickelectric** [comment]
> Consolidate is failing because of the trailing comma [here](https://github.com/patrickelectric/blueos-node-red/blob/master/Dockerfile?rgh-link-date=2023-08-30T05%3A10%3A38Z#L48C13-L48C14) (we're handling the labels using JSON, which doesn't allow a comma after the last item in a list).

image

**Comment by patrickelectric** [comment]
> Consolidate is failing because of the trailing comma [here](https://github.com/patrickelectric/blueos-node-red/blob/master/Dockerfile#L48C13-L48C14) (we're handling the labels using JSON, which doesn't allow a comma after the last item in a list).

Fixed.

**Review by ES-Alexander — APPROVED** [review]
LGTM, although we should have a discussion about description lengths - if they're more than about 10 words they end up covering multiple lines in their card, which ends up looking weird in [the gallery](https://docs.bluerobotics.com/BlueOS-Extensions-Repository/).

**Pull request merged**
