### PR TITLE
Add Cerulean Manuals

### PR DESCRIPTION
**Pull request by NickNothom**

### CODE REVIEW

**Comment by Williangalvani** [comment]
can you get rid of the merge commit?

**Comment by patrickelectric** [comment]
You can break in two commits, once for the cerulean rename and the other for the new extension.
But.. since it's a simple and we are still small, a single commit would not hurt, the important part is to remove the merge commit.

**Comment by NickNothom** [comment]
I had to rebuild my DVL image with `--provenance=false` to get the checks to pass.

**Review by patrickelectric — APPROVED** [review]

**Comment by patrickelectric** [comment]
> I had to rebuild my DVL image with `--provenance=false` to get the checks to pass.

Thanks for informing it!

**Pull request merged**
